# Generated by Django 4.2 on 2025-08-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactus_alter_workersreg_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersreg',
            name='jobstatus',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('completed', 'Completed')], default='available', max_length=20),
        ),
    ]
